version: '3'
services:
  jetx:
    build: .

    container_name: jetx 
    
    volumes:
      
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/tmp/argus_socket:/tmp/argus_socket"
      
      - "~/.funcx/:/root/.funcx/"
      
      - "~/SP21_jetson-container/Input:/app/Input/"
      - "~/SP21_jetson-container/Output:/app/Output/"
      - "~/SP21_jetson-container/Xtra:/app/Xtra"
      
    #devices: 
      #- "/dev/video0:/dev/video0"

    network_mode: "host"
    
    environment:
      - "DISPLAY"

    #stdin_open: true
    tty: true
    #entrypoint: /bin/bash
    #command: "/bin/bash"
