version: '3'
services:
  jetx:
    build: .

    container_name: jetx 
    
    volumes:
      
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/tmp/argus_socket:/tmp/argus_socket"
      
      - "~/.funcx/:/root/.funcx/"
      
      - "~/SP21/output:/app/output/"
      - "~/SP21/sensor-sim:/app/sensor-sim/"
      - "~/SP21/JetsonYolo:/app/JetsonYolo/"
      - "~/SP21/yolov5:/app/yolov5"
      
    devices: 
      - "/dev/video0:/dev/video0"

    network_mode: "host"
    
    environment:
      - "DISPLAY"

    #stdin_open: true
    tty: true
    #entrypoint: /bin/bash
    #command: "/bin/bash"
